%YAML 1.2
---
# Configuration
sonar_pointcloud:
    pointcloudFrame: map

# List of Sonars
sonars:
    - sonar0
    - sonar1

sonar0:
    topic: ultrasound/sonar
    transform:
        frame: sonar0
        posX: 2.3
        posY: 0.8
        posZ: 2.5
        roll: 0
        pitch: 0
        yaw: 0
sonar1:
    topic: ultrasound/sonar
    transform:
        frame: sonar1
...
